language: ruby
dist: xenial
before_install:
  - if [[ $TRAVIS_RUBY_VERSION =~ ^2\.[12]\. ]]; then gem install rubygems-update --version '~> 2.7' --no-document && update_rubygems; else gem update --system; fi
  - gem --version
  - if [[ $TRAVIS_RUBY_VERSION =~ ^2\.[12]\. ]]; then gem install bundler --version '~> 1.17'; else gem install bundler; fi
  - bundle --version
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-9.1.17.0
  - jruby-9.2.9.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
