language: ruby
sudo: false
before_script:
  - bundle update
cache: bundler
rvm:
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-9.0.5.0
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.0.5.0
    - rvm: jruby-head
