image: Visual Studio 2019
version: "{build}-{branch}"

cache:
  - vendor/bundle

environment:
  TESTOPTS: --verbose

  matrix:
    - RUBY_ENGINE: ruby
      RUBY_VERSION: 21

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 21-x64

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 22

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 22-x64

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 23

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 23-x64

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 24

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 24-x64

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 25

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 25-x64

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 26

    - RUBY_ENGINE: ruby
      RUBY_VERSION: 26-x64

    - RUBY_ENGINE: jruby
      JRUBY_VERSION: 9.1.17.0

    - RUBY_ENGINE: jruby
      JRUBY_VERSION: 9.2.9.0

install:
  - if not exist vendor mkdir vendor
  - if %RUBY_ENGINE%==jruby appveyor DownloadFile https://repo1.maven.org/maven2/org/jruby/jruby-dist/%JRUBY_VERSION%/jruby-dist-%JRUBY_VERSION%-bin.zip -FileName vendor\jruby-dist-%JRUBY_VERSION%-bin.zip
  - if %RUBY_ENGINE%==jruby 7z x vendor\jruby-dist-%JRUBY_VERSION%-bin.zip -ovendor -y
  - if %RUBY_ENGINE%==jruby set PATH=C:\projects\putty-key\vendor\jruby-%JRUBY_VERSION%\bin;%PATH%
  - if %RUBY_ENGINE%==jruby gem install bundler
  - if %RUBY_ENGINE%==ruby set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle update

build: off

before_test:
  - "%RUBY_ENGINE% -v"
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test

after_test:
  - bundle clean
